### ISSUE TITLE
General suggestions

### ISSUE THREAD

**Issue by captn3m0** [WordImpress/CampTix-Razorpay#3]
I work at Razorpay, and had some general suggestions around improvements:

1. You don't seem to be capturing payments. I'd recommend moving to the to [orders API](https://docs.razorpay.com/v1/page/orders) to automatically capture payments. For our other plugins, we usually give the merchant a choice whether they want automatic capture or not. If a payment is not captured, we will auto-refund it, and this might be a bad experience for the merchant if left unexplained.
2. You seem to be asking for key_secret, but not using it anywhere that I could find. Is that intentional?

The ideal flow for our plugins (you can see our other integrations: https://razorpay.com/integrations/ for reference) is:

1. Create a order on the backend using the orders API (with payment_capture=1 by default)
2. Show the checkout form and process the payment using checkout.js
3. Verify the signature and mark the order as processed on the platform end (this would be camptix).

If you have any questions, I'll be more than happy to answer them here. We'd love to add this to the "Community Integrations" section once you have a stable release.

**Comment by ravinderk** [comment]
@captn3m0 I will make changes to this plugin as you suggested.

**Comment by ravinderk** [comment]
@captn3m0 I update following things in the plugin:
1. capture payment
for ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L441

2. Extra setting removed
For ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L198

**Comment by captn3m0** [comment]
You are still using the post-payment-capture, and while this works, we are migrating all our plugins to the Orders API, which gives merchants more visibility into the order retry mechanism. (Each order can be retried multiple times, and while it creates multiple payments, they are all linked).

I'd recommend moving to the Orders API. (It is just changing the capture call to a orders.create call and adding the output of that to checkout as `order_id` parameter.

**Comment by ravinderk** [comment]
@captn3m0 Can we use `Order API` with checkout js?

**Comment by captn3m0** [comment]
Yes, Orders API is meant to be used with Checkout. Take a look at our 
php test app: https://github.com/razorpay/razorpay-php-testapp for 
exact steps.

**Comment by ravinderk** [comment]
@captn3m0 Logic updated. Now plugin totally depend upon order api
for ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L204

**Comment by ravinderk** [comment]
@captn3m0 Close this issue for now. Let me know if I miss something

**Comment by captn3m0** [comment]
@ravinderk There is a security issue in the current implementation, where you are not doing any  of the signature that we pass. (see point 3 in OP). The right way for this is:

1. Create an order and store the order id (session/db)
2. display the checkout form
3. Verify the `razorpay_payment_id` and `razorpay_signature` with the stored `order_id`

We have a verifySignature method present in our Razorpay PHP SDK that you can utilize for the same. Just ensure that the order id that you pass comes from a safe store, and not user input.

**Comment by ravinderk** [comment]
@captn3m0 Thank you for suggestion, I will look into this

**Comment by ravinderk** [comment]
@captn3m0 Follow changes made to code as per your suggestion.
1. Now session manages for each ticket purchase. A session starts when a user selects ticker after applying a coupon if any and process to checkout and session end when either payment failed or success.
For ref:
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L210
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L485
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L551

2. Each Razorpay payment will be verified after payment complete.
https://github.com/WordImpress/CampTix-Razorpay/blob/master/assets/frontend/js/camptix-razorpay-popup.js#L145
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L98
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L773

Let me know if anything else I missed.

**Comment by captn3m0** [comment]
Can you clarify the verify_payment usage? It seems to be getting called post payment, but the result of the verification isn't affecting anything.

1. Verification should include the razorpay_order_id from the session
2. Verification success should mark order as paid
3. Verification failure should mark order as failed.

See [this](https://github.com/razorpay/razorpay-woocommerce/blob/85d360fca28a1782e3d14b37bd80bd4faf9d70f3/razorpay-payments.php#L692-L696), [this](https://github.com/razorpay/razorpay-woocommerce/blob/85d360fca28a1782e3d14b37bd80bd4faf9d70f3/razorpay-payments.php#L652-L668) and [this](https://github.com/razorpay/razorpay-woocommerce/blob/85d360fca28a1782e3d14b37bd80bd4faf9d70f3/razorpay-payments.php#L756-L768) for eg.

**Comment by ravinderk** [comment]
@captn3m0 
1. I am verifying session order id
For Ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L761

2. Order will be automatically handled by [Camptix](https://github.com/Automattic/camptix) plugin,
    So after verifying payment user will automatically redirect to related url and these url will be handled by camp tix.
    For ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/assets/frontend/js/camptix-razorpay-popup.js#L149
**Complete payment**
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L483
**Failed payment**
https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L512

Wha do you think?

**Comment by captn3m0** [comment]
My understanding:

1. handler is function by razorpay JS
2. handler calls [`verify_payment`](https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L748-L785) over AJAX
3. this returns a true/false result
4. which is used to redirect the user to the success/failure page

What if I (as an attacker) decide to set a breakpoint on the handler function, prevent it from being called, and instead directly call `$response.data.return_url`? Would the payment be marked as succesfull?

**Comment by ravinderk** [comment]
@captn3m0 
1. Now payment will be verified on server side rather then ajax
For ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L466

2. I added verification also on success page  for payment in case hacker try to hijack itl
For ref: https://github.com/WordImpress/CampTix-Razorpay/blob/master/inc/class-camptix-payment-method-razorpay.php#L521

**Comment by captn3m0** [comment]
Looks good. Although, if you're just going to be validating the payment post that ajax request anyway, you can likely drop the ajax processing part entirely.

**Comment by ravinderk** [comment]
@captn3m0 I am not using Ajax to validate payment. I am using ajax only to create address because I will order required information on checkout page only.
